# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  user: postgres
  password: password
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  adapter: postgresql
  database: myapp_production
  pool: 5
  encoding: unicode


  
